// Generated by https://quicktype.io

export interface CatalogoServicios {
  servicioId:            number;
  nombreServicio:        string;
  precioServicio:        string;
  descripcionServicio:   string;
  direccionRecurso:      string;
}