// Generated by https://quicktype.io

export interface Cotizaciones {
  cotizacionId:          number;
  clienteNombreApellido: string;
  corpEmail:             string;
  fechaInicio:           string;
  fechaEntrega:          string;
  tipoServicio:          string;
  cotizacionDescripcion: string;
}
