// Generated by https://quicktype.io

export interface Entregas {
  nombre_apellido:    string;
  correo_electronico: string;
  nombre_proyecto:    string;
  fecha_entrega:      string;
  hora_entrega:       string;
  lugar_entrega:      string;
}
