// Generated by https://quicktype.io

export interface Proyectos {
  project_id:          string;
  project_name:        string;
  tipo_servicio:       string;
  client_name:         string;
  client_email:        string;
  start_date:          string;
  end_date:            string;
  project_description: string;
}
