// Generated by https://quicktype.io

export interface Requerimientos {
  requerimiento_id:          string;
  project_id:                string;
  tipo_requerimiento:        string;
  proyecto:                  string;
  resumen_requerimiento:     string;
  prioridad:                 string;
  descripcion_requerimiento: string;
}
